image: ubuntu:vivid

before_script:
  - apt-get update
  - apt-get install -y curl file build-essential libssl-dev libpcap-dev

cache:
  untracked: true
  key: "$CI_BUILD_NAME"
  paths:
    - $HOME/.cargo
    - $CI_PROJECT_DIR/target

stages:
  - test

test-nightly:
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo --channel=nightly
    - cargo build --release --verbose
    - cargo test --verbose
